In [29]:
# titanic.ipynb

In [30]:
# 1. 匯入訓練資料
import pandas as pd
train_df = pd.read_csv("train.csv", encoding="utf-8")
train_df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [31]:
test_df = pd.read_csv("test.csv", encoding="utf-8")
test_df

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...
413,1305,3,"Spector, Mr. Woolf",male,NaN,0,0,A.5. 3236,8.0500,NaN,S
414,1306,1,"Oliva y Ocana, Dona. Fermina",female,39.0,0,0,PC 17758,108.9000,C105,C
415,1307,3,"Saether, Mr. Simon Sivertsen",male,38.5,0,0,SOTON/O.Q. 3101262,7.2500,NaN,S
416,1308,3,"Ware, Mr. Frederick",male,NaN,0,0,359309,8.0500,NaN,S
417,1309,3,"Peter, Master. Michael J",male,NaN,1,1,2668,22.3583,NaN,C

In [32]:
# 2. 補缺失值
# 數值類型:中位數、類別類型:最常出現值

In [33]:
# 資料集各欄位的缺失值總數，找出中位數並且填補
train_df.isna().sum()
test_df.isna().sum()

PassengerId      0
Pclass           0
Name             0
Sex              0
Age             86
SibSp            0
Parch            0
Ticket           0
Fare             1
Cabin          327
Embarked         0
dtype: int64

In [34]:
med = train_df.median()
train_df = train_df.fillna(med)
test_df = test_df.fillna(med)

<ipython-input-34-566a93fcf168>:1: FutureWarning: The default value of numeric_only in DataFrame.median is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  med = train_df.median()

In [35]:
train_df.isna().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age              0
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [36]:
# 登船口:C：Cherbourg、Q：Queenstown、S：Southampton
most = train_df["Embarked"].value_counts().idxmax()
train_df["Embarked"] = train_df["Embarked"].fillna(most)
test_df["Embarked"] = train_df["Embarked"].fillna(most)

In [37]:
train_df.isna().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age              0
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         0
dtype: int64

In [38]:
# 3. One-Hot Encoding
#目的:多個類別的分類變量轉換為機器學習模型可以處理的數字形式。
#核心:每個向量，向量的長度等於所有可能的類別數量，該向量中只有一個元素為1，其他元素為0。

In [39]:
def nameflow(s):
  #s = "Braund, Mr. Owen Harris"
  s = s.split(",")[-1].split(".")[0]
  return s.strip()
train_df["Name"].apply(nameflow).value_counts()

Mr              517
Miss            182
Mrs             125
Master           40
Dr                7
Rev               6
Mlle              2
Major             2
Col               2
the Countess      1
Capt              1
Ms                1
Sir               1
Lady              1
Mme               1
Don               1
Jonkheer          1
Name: Name, dtype: int64

In [40]:
def nameflow(s):
  reserved = ["Mr","Mrs","Miss","Master"]
  s = s.split(",")[-1].split(".")[0]
  s = s.strip()
  reserved = ["Mr","Mrs","Miss","Master"]
  if s in reserved:
    return s
  else:
    return None

In [41]:
train_df["Name"] = train_df["Name"].apply(nameflow)
test_df["Name"] = test_df["Name"].apply(nameflow)
test_df["Name"]

0          Mr
1         Mrs
2          Mr
3          Mr
4         Mrs
        ...
413        Mr
414      None
415        Mr
416        Mr
417    Master
Name: Name, Length: 418, dtype: object

In [42]:
# one-hot encoding
train = pd.get_dummies(train_df, columns=["Name", "Sex", "Embarked"])
test = pd.get_dummies(test_df, columns=["Name", "Sex", "Embarked"])

In [43]:
train.columns # 顯示欄位名稱
train = train.drop(["PassengerId", "Ticket", "Cabin"], axis=1)
test = test.drop(["Ticket", "Cabin"], axis=1)

In [44]:
x_train = train.drop(["Survived"], axis=1)
y_train = train["Survived"]
x_predict = test.drop(["PassengerId"], axis=1)
pid = test["PassengerId"]

In [48]:
# 4. 模型訓練
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import GridSearchCV

In [56]:
# 使用 GridSearchCV 尋找最佳參數
clf = RandomForestClassifier()
params = {
    "n_estimators":range(19, 25),
    "max_depth":range(5,9)
}
grid_search = GridSearchCV(clf, params, cv=10, n_jobs=4)
grid_search.fit(x_train, y_train)
print("最佳參數:", grid_search.best_params_)
print("最佳分數:", grid_search.best_score_)

最佳參數: {'max_depth': 8, 'n_estimators': 23}
最佳分數: 0.8418227215980025

In [57]:
# 5. 模型評估
import numpy as np
from sklearn.model_selection import cross_val_score

In [58]:
# 交叉驗證評估模型性能
clf = RandomForestClassifier(n_estimators=23,
                       max_depth=8)
scores = cross_val_score(clf,
                         x_train,
                         y_train,
                         cv=10,
                         n_jobs=4)  # 使用交叉驗證評估模型性能
print("十次分數:", scores)
print("平均分數:", np.average(scores))

十次分數: [0.78888889 0.86516854 0.76404494 0.91011236 0.86516854 0.85393258
 0.82022472 0.78651685 0.87640449 0.84269663]
平均分數: 0.8373158551810237

In [60]:
# 6. 模型預測
clf = RandomForestClassifier(n_estimators=23,
                       max_depth=8)
clf.fit(x_train, y_train)
pre = clf.predict(x_predict)
pre

array([0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1,
       1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1,
       1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0,
       1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1,
       0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0,
       1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1,
       0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0,
       1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0,
       0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0,
       1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1,
       0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1])

In [61]:
# 7. 生成預測結果文件
result = pd.DataFrame({
    "PassengerId":pid,
    "Survived":pre
})
result.to_csv("titanic_rf.csv", encoding="utf-8", index=False)
result

     PassengerId  Survived
0            892         0
1            893         0
2            894         0
3            895         0
4            896         1
..           ...       ...
413         1305         0
414         1306         1
415         1307         0
416         1308         0
417         1309         1

[418 rows x 2 columns]